# Etapa 3: Análisis de datos utilizando SQL


## Objetivos

En esta práctica subiremos los datos a una base de datos SQL y realizaremos diferentes queries para obtener información sobre los datos

In [1]:
!pip install sqlalchemy==1.4.16 --quiet
import pandas as pd
import numpy as np
!pip install PyMySQL --quiet
import pymysql as pymsql
!pip install mysql-connector --quiet
import mysql.connector
from sqlalchemy import create_engine
!pip install sqlalchemy-utils --quiet
from sqlalchemy_utils import database_exists, create_database
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 48.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for sqlalchemy (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.4.16 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 1.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 17.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for mysql-connector (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.6/92.6 kB 1.9 MB/s eta 0:00:00


### Tarea 1: Subir los datos a la base de datos:

Primero cargamos el archivo de datos `dataset_part_2.csv`.

In [2]:
df_path = "dataset_part_2.csv"
df = pd.read_csv(df_path)

In [3]:
#Rellena la siguiente variable con tu nombre y apellido (Todo junto y sin espacios).
nameDB = 'AhmedBouallou'
linkConexion = 'mysql+mysqlconnector://alumno:385bd4cf713a8a36@35.180.211.139/' + nameDB
#Establecemos la conexión
engine = create_engine(linkConexion)

In [4]:
if not database_exists(engine.url):
    create_database(engine.url)

In [5]:
# Añadir el dataframe a sql SPACEXTBL usando la función to_sql().
df.to_sql("SPACEXTBL",engine)

-1

In [14]:
query = "select * from SPACEXTBL;"
df  = pd.read_sql(query, engine )
df
# We are telling read_sql to use the 'engine' object to establish a connection to the database and execute the SQL query defined in the 'query' variable

,index,FlightNumber,Date,BoosterVersion,PayloadMass,Payload,Orbit,LaunchSite,LandingOutcome,Flights,GridFins,Reused,Legs,LandingPad,Block,Customers,Mission_Outcome,ReusedCount,Serial,Longitude,Latitude,Class
0,0,1,2010-06-04,Falcon 9,6123.547647,Dragon Qualification Unit,LEO,CCSFS SLC 40,None None,1,0,0,0,None,1.0,SpaceX,1,0,B0003,-80.577366,28.561857,0
1,1,2,2012-05-22,Falcon 9,525.000000,COTS Demo Flight 2,LEO,CCSFS SLC 40,None None,1,0,0,0,None,1.0,NASA(COTS),1,0,B0005,-80.577366,28.561857,0
2,2,3,2013-03-01,Falcon 9,677.000000,CRS-2,ISS,CCSFS SLC 40,None None,1,0,0,0,None,1.0,NASA (CRS),1,0,B0007,-80.577366,28.561857,0
3,3,4,2013-09-29,Falcon 9,500.000000,CASSIOPE,PO,VAFB SLC 4E,False Ocean,1,0,0,0,None,1.0,MDA,1,0,B1003,-120.610829,34.632093,0
4,4,5,2013-12-03,Falcon 9,3170.000000,SES-8,GTO,CCSFS SLC 40,None None,1,0,0,0,None,1.0,SES,1,0,B1004,-80.577366,28.561857,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,85,86,2020-09-03,Falcon 9,15600.000000,Starlink-11,VLEO,KSC LC 39A,True ASDS,2,1,1,1,5e9e3032383ecb6bb234e7ca,5.0,SpaceX,1,12,B1060,-80.603956,28.608058,1
86,86,87,2020-10-06,Falcon 9,15600.000000,Starlink-12,VLEO,KSC LC 39A,True ASDS,3,1,1,1,5e9e3032383ecb6bb234e7ca,5.0,SpaceX,1,13,B1058,-80.603956,28.608058,1
87,87,88,2020-10-18,Falcon 9,15600.000000,Starlink-13,VLEO,KSC LC 39A,True ASDS,6,1,1,1,5e9e3032383ecb6bb234e7ca,5.0,SpaceX,1,12,B1051,-80.603956,28.608058,1
88,88,89,2020-10-24,Falcon 9,15600.000000,Starlink-14,VLEO,CCSFS SLC 40,True ASDS,3,1,1,1,5e9e3033383ecbb9e534e7cc,5.0,SpaceX,1,12,B1060,-80.577366,28.561857,1
89,89,90,2020-11-05,Falcon 9,3681.000000,GPS III SV04 (Sacagawea),MEO,CCSFS SLC 40,True ASDS,1,1,0,1,5e9e3032383ecb6bb234e7ca,5.0,United States Space Force,1,8,B1062,-80.577366,28.561857,1

## Tarea 2: Queries con SQL

### Ejercicio 1

##### Muestra las diferentes plataformas de lanzamiento:

In [20]:
#Rellena la variable query con tu consulta
query = """  SELECT DISTINCT LaunchSite
             FROM SPACEXTBL  """
df  = pd.read_sql(query, con = engine )
df

# SELECT
#   DISTINCT <column_1>
# FROM
#   <table>;

     LaunchSite
0  CCSFS SLC 40
1   VAFB SLC 4E
2    KSC LC 39A

### Ejercicio 2

##### Muestra 5 lanzamientos cuya plataforma empiece por 'CCS'

In [25]:
#Rellena la variable query con tu consulta
# SELECT column_name
# FROM table_name
# WHERE column_name LIKE 'variable%';

# 'query' contains an SQL query that will be executed against a database
#  triple double quotes are often used for multi-line strings
query = """  SELECT *
             FROM SPACEXTBL
             WHERE LaunchSite LIKE 'CCS%'
             LIMIT 5;  """
df  = pd.read_sql(query, con = engine )
df

# If I want to select a range of rows in two columns:
# SELECT column1, column2 or *
# FROM table_name
# LIMIT offset, count;
# 'offset' is the starting row number (0-based index) from where you want to begin fetching rows
# 'count' is the number of rows you want to retrieve

,index,FlightNumber,Date,BoosterVersion,PayloadMass,Payload,Orbit,LaunchSite,LandingOutcome,Flights,GridFins,Reused,Legs,LandingPad,Block,Customers,Mission_Outcome,ReusedCount,Serial,Longitude,Latitude,Class
0,0,1,2010-06-04,Falcon 9,6123.547647,Dragon Qualification Unit,LEO,CCSFS SLC 40,None None,1,0,0,0,None,1.0,SpaceX,1,0,B0003,-80.577366,28.561857,0
1,1,2,2012-05-22,Falcon 9,525.000000,COTS Demo Flight 2,LEO,CCSFS SLC 40,None None,1,0,0,0,None,1.0,NASA(COTS),1,0,B0005,-80.577366,28.561857,0
2,2,3,2013-03-01,Falcon 9,677.000000,CRS-2,ISS,CCSFS SLC 40,None None,1,0,0,0,None,1.0,NASA (CRS),1,0,B0007,-80.577366,28.561857,0
3,4,5,2013-12-03,Falcon 9,3170.000000,SES-8,GTO,CCSFS SLC 40,None None,1,0,0,0,None,1.0,SES,1,0,B1004,-80.577366,28.561857,0
4,5,6,2014-01-06,Falcon 9,3325.000000,Thaicom 6,GTO,CCSFS SLC 40,None None,1,0,0,0,None,1.0,Thaicom,1,0,B1005,-80.577366,28.561857,0

### Ejercicio 3

##### Mustra el la masa total transportada por los lanzamientos realizados donde el cliente es NASA (CRS)

In [27]:
# Customers
# PayloadMass

query = """  SELECT FlightNumber, SUM(PayloadMass) AS TotalPayloadMass
              FROM SPACEXTBL
              WHERE Customers = 'NASA (CRS)'
              GROUP BY FlightNumber;  """
df  = pd.read_sql(query, con = engine )
df

    FlightNumber  TotalPayloadMass
0              3             677.0
1              7            2296.0
2             11            2216.0
3             12            2395.0
4             14            1898.0
5             16            2477.0
6             20            3136.0
7             23            2257.0
8             27            2490.0
9             32            2708.0
10            36            2910.0
11            42            2205.0
12            48            2760.0
13            52            2410.0
14            60            2573.0
15            64            2482.0
16            67            2227.7
17            70            5000.0
18            76            1977.0

### Ejercicio 4

##### Muestra la masa media tranportada por lanzamientos con serie que comienza por B1

In [29]:
query = """ SELECT ROUND(AVG(PayloadMass))
            FROM SPACEXTBL
            WHERE serial LIKE 'B1%' ;"""
df  = pd.read_sql(query, con = engine )
df

   ROUND(AVG(PayloadMass))
0                   6251.0

### Ejercicio 5

##### Muestra la fecha donde se realizo el primer aterrizaje exitoso sobre terreno (TRUE RTLS)

*Pista:Utiliza la función min*

In [34]:
# Most efficient form:
query = """ SELECT FlightNumber, BoosterVersion, LandingOutcome, MIN(Date)
FROM SPACEXTBL
WHERE LandingOutcome = 'True RTLS'; """
df  = pd.read_sql(query, con = engine )
df

   FlightNumber BoosterVersion LandingOutcome   MIN(Date)
0            17       Falcon 9      True RTLS  2015-12-22

### Ejercicio 6

##### Muestra las series de los cohetes que aterrizaron sobre portaviones (TRUE ASDS) con una masa entre 4000 y 6000

In [35]:
query = """ SELECT BoosterVersion, LandingOutcome, PayloadMass
FROM SPACEXTBL
WHERE LandingOutcome = 'True ASDS' AND PayloadMass BETWEEN 4000 AND 6000 ; """
df  = pd.read_sql(query, con = engine )
df

  BoosterVersion LandingOutcome  PayloadMass
0       Falcon 9      True ASDS       4696.0
1       Falcon 9      True ASDS       4600.0
2       Falcon 9      True ASDS       5300.0
3       Falcon 9      True ASDS       5200.0
4       Falcon 9      True ASDS       5800.0
5       Falcon 9      True ASDS       4000.0
6       Falcon 9      True ASDS       5000.0

### Ejercicio 7

##### Muestra el numero de lanzamientos que completaron su mision correctamente y aquellos que fallaron

In [45]:
query = """
SELECT Mission_Outcome AS 'Mission Value',
  CASE WHEN Mission_Outcome = 0 THEN 'Mission Failed'
       WHEN Mission_Outcome = 1 THEN 'Mission Accomplished'
  END AS 'Mission Status',
  COUNT(*) AS 'Total'
FROM SPACEXTBL
GROUP BY Mission_Outcome ; """
df = pd.read_sql(query, con = engine)
df

# From my query, I've given the column 'Mission_Outcome' an alias of 'Mission Outcome'
# Whatever I put in my CASE are my options and END AS is the name of the column the two CASE WHEN (x2)
# COUNT(*) is used to count all the rows or records in the table

   Mission Value        Mission Status  Total
0              0        Mission Failed      2
1              1  Mission Accomplished     88

### Ejercicio 8

##### Muestra las series de los cohetes que transportaron la masa máxima

In [64]:
# What we need to do is first find the maximum mass that any rocket has ever taken
# And then, we see which rockets, by their serial number, carried that maximum payload weight..
query = """
SELECT FlightNumber, Serial, PayloadMass AS 'Max. Mass'
FROM SPACEXTBL
WHERE PayloadMass = (
  SELECT MAX(PayloadMass)
  FROM SPACEXTBL); """
df  = pd.read_sql(query, con = engine )
df

    FlightNumber Serial  Max. Mass
0             69  B1048    15600.0
1             72  B1049    15600.0
2             74  B1051    15600.0
3             75  B1056    15600.0
4             77  B1048    15600.0
5             78  B1051    15600.0
6             80  B1049    15600.0
7             81  B1059    15600.0
8             84  B1049    15600.0
9             86  B1060    15600.0
10            87  B1058    15600.0
11            88  B1051    15600.0
12            89  B1060    15600.0

### Ejercicio 9

##### Muestra los el resultados del aterrizaje, la serie del cohete y las plataforma de lanzamiento de aquellos lanzamientos fallidos o no intentados en el año 2015

In [ ]:
query = """
SELECT
FROM SPACEXTBL
WHERE ; """
df  = pd.read_sql(query, con = engine )
df

### Ejercicio 10

##### Muestra los resultados y la frecuencia de estos resultados entre 2010-06-04 y 2017-03-20 ordenados en orden descendiente según la frecuencia

In [ ]:
query = """
SELECT
FROM SPACEXTBL
WHERE ; """
df  = pd.read_sql(query, con = engine )
df